# Generated by Django 4.0 on 2021-12-12 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_allergy_drink_drinkallergy_subcategory_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drink',
            name='name_en',
        ),
    ]
