# Generated by Django 4.0 on 2021-12-12 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_remove_drink_name_en'),
    ]

    operations = [
        migrations.RenameField(
            model_name='drink',
            old_name='name_kr',
            new_name='name',
        ),
    ]
