# Generated by Django 4.0 on 2021-12-13 05:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_allergy_drink_categories_drinks_images_menu_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='allergy_drink',
            old_name='allergy_id',
            new_name='allergy',
        ),
        migrations.RenameField(
            model_name='allergy_drink',
            old_name='drink_id',
            new_name='drink',
        ),
        migrations.RenameField(
            model_name='categories',
            old_name='menu_id',
            new_name='menu',
        ),
        migrations.RenameField(
            model_name='drinks',
            old_name='category_id',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='drinks',
            old_name='english_name',
            new_name='en_name',
        ),
        migrations.RenameField(
            model_name='drinks',
            old_name='korean_name',
            new_name='kr_name',
        ),
        migrations.RenameField(
            model_name='images',
            old_name='drink_id',
            new_name='drink',
        ),
        migrations.RenameField(
            model_name='nutritions',
            old_name='drink_id',
            new_name='drink',
        ),
        migrations.RenameField(
            model_name='nutritions',
            old_name='one_serving_kca',
            new_name='one_serving_kcal',
        ),
        migrations.RenameField(
            model_name='nutritions',
            old_name='size_id',
            new_name='size',
        ),
    ]
